### Ping
curl -X POST http://localhost:3000/mcp \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "id": "1234",
    "method": "ping"
  }'

### List tools
curl -X POST http://localhost:3000/mcp \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "id": "1234",
    "method": "tools/list"
  }'

### Call tool
curl -X POST http://localhost:3000/mcp \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "id": "1234",
    "method": "tools/call",
    "params": {
      "name": "random",
      "arguments": {
        "min": 1,
        "max": 100
      }
    }
  }'

